name: Publish to NPMJS and GPR

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: dev

    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: '10.15.1'
        registry-url: 'https://registry.npmjs.org'
        scope: '@elistone'

    - name: Configure git
      run: |
        git config user.email "noreply@github.com"
        git config user.name "Actions User"

    # Publish to npm
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'
        scope: '@elistone'

    - name: Authenticate with the GitHub Package Registry
      run:
        echo "//npm.pkg.github.com:_authToken=${{ secrets.GH_PACKAGE_TOKEN }}" >
        ~/.npmrc

    # Publish to GitHub Packages
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
